### ISSUE TITLE
Illegal Instruction on Archlinux ARM on Raspberry Pi

### ISSUE THREAD

**Issue by apirogov** [japaric/ruststrap#37] opened 2015-06-04 22:08 UTC
I tried both 1.0.0 and nightly (2015-06-03), just called rustc without arguments and got "Illegal Instruction" error.

I use Archlinux ARM on a Raspberry Pi.

**Comment by japaric** [comment] 2015-06-04 22:37
@apirogov Could you try [this older version](https://www.dropbox.com/sh/qfbt03ys2qkhsxs/AAAJi8Z-bBWvExG_z5DzuxN2a/will_be_deleted?dl=0)? I made a change in the build system between that version and the 1.0.0, and I think that may be the cause of the problem.

**Comment by apirogov** [comment] 2015-06-07 12:54
This works! At least running rustc gives me a list of commands instead of an error, so I assume it does.

**Comment by japaric** [comment] 2015-06-07 16:03
> This works! Successfully compiled a hello world with it! Thanks!

OK, then the problem is that I moved the Rust builder from Raspbian to Debian Wheezy (because of #30). When building rust on Wheezy one of the dependencies must be injecting an ARMv7 specific instruction that can't be executed in the RPi, which is an ARMv6 device (this has [happened before](https://github.com/japaric/ruststrap/issues/18#issuecomment-72863370)).

The solution is to move back the builder to Raspbian. I'll try build rust on Raspbian, but if I still hit #30 then there isn't much I can do.

> Do you have an according snapshot of cargo? I tried some older ones,

I restored some snapshots, check [the will_be_deleted folder](https://www.dropbox.com/sh/qfbt03ys2qkhsxs/AACxFoD1OrxDXURzj5wX0IYUa?dl=0).

**Comment by japaric** [comment] 2015-06-07 22:50
I managed to build rust in (a more recent) Raspbian, @apirogov could you try [this tarball](https://www.dropbox.com/sh/qfbt03ys2qkhsxs/AADXECggzC_D70E5ZpD7jiT2a/rpi_test?dl=0)?

**Comment by apirogov** [comment] 2015-06-11 15:32
It works!

**Comment by japaric** [comment] 2015-06-11 16:05
@apirogov Excellent! I'll start a cargo build now, if that also works then I'll move my builder back to Raspbian. I'll ping you later so you can help me testing cargo :-).

**Comment by japaric** [comment] 2015-06-11 20:52
@apirogov I've uploaded a new [cargo tarball](https://www.dropbox.com/sh/qfbt03ys2qkhsxs/AADXECggzC_D70E5ZpD7jiT2a/rpi_test?dl=0), can you give it a try?

**Comment by apirogov** [comment] 2015-06-16 13:04
It works too :)

One minor thing - when executed, cargo gives every time this warning:
cargo: /usr/lib/libssl.so.1.0.0: no version information available (required by cargo)

It does not seem to have any negative effect though, or I did not run in such cases. This warning also comes with old builds (like 2015-04-30-efb482d).

**Comment by japaric** [comment] 2015-06-16 14:42
> It works too :)

Great, I've switch the builders back to raspbian, so all new nightlies should work on the RPi. I've also started a rebuild of the 1.0.0 and 1.1.0-beta tarballs, the new versions should work on the RPi.

> One minor thing - when executed, cargo gives every time this warning:

Yeah, I get that too when running cargo under ArchLinux ARM, but not under Raspbian. I think is harmless tough.

**Comment by japaric** [comment] 2015-06-17 22:21
The builder has been migrated back to raspbian, and I've rebuild the 1.0.0 and 1.1.0-beta tarballs. So I'm going to close this as fixed. @apirogov Do let me know if you encounter any other issue, and thanks for helping me test the tarballs!

**Closed by japaric** 2015-06-17 22:21 UTC
